### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by neithanmo**

### CODE REVIEW

**Comment by ftheirs** [comment]
Can we have a clean API instead of using the curve in the function name?
For example instead of using **SignSECP256K1**, replace this with **Sign**. However, it might be a good idea to keep the old methods for backward compatibility but with a `// Deprecated: use X function instead`

**Comment by neithanmo** [comment]
> Can we have a clean API instead of using the curve in the function name? For example instead of using **SignSECP256K1**, replace this with **Sign**. However, it might be a good idea to keep the old methods for backward compatibility but with a `// Deprecated: use X function instead`

done! :+1:

**Review by ftheirs — APPROVED** [review]

**Comment by Stebalien** [comment]
That PR was just switching back to upstream, IIRC. We should be able to switch to `.Sign` without any issues.

**Comment by Stebalien** [comment]
Ah, I see. This is _adding_ a `Sign` method. I thought that ship had already sailed.

Yes, I agree, that change should be reverted.

**Pull request merged**
